linters:
  ColorVariable:
    enabled: false
  EmptyRule:
    enabled: false
  IdSelector:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
